# Generated by Django 5.2 on 2025-05-04 21:38

import app.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='encrypted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_path',
            field=models.FileField(upload_to=app.utils.get_user_upload_path),
        ),
    ]
